export { default as Contact } from './Contact/query'
export { default as Content } from './Content/query'
export { default as DynamicContent } from './DynamicContent/query'
export { default as Heading } from './Heading/query'
export { default as Hero } from './Hero/query'
export { default as LinkedMediaGrid } from './LinkedMediaGrid/query'
export { default as MediaGrid } from './MediaGrid/query'
